version: '3.3'

services:

  devita_crawler:
    container_name: devita_crawler
    image: italia/developers-italia-backend
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - overlay

networks:
  overlay:
