on:
  push:
    branches:
      - github_action_test
  pull_request:

name: ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.13.15'

      - run: cd crawler && make build
      - run: cd crawler && make test

  build_and_publish_docker_image:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - run: ls -la
      - name: Get Docker image tags
        id: image_tags
        run: |
          IMAGE=italia/developers-italia-backend

          TAGS=${IMAGE}:latest
          TAGS="$TAGS,${IMAGE}:${GITHUB_SHA::8}"

          echo ::set-output name=tags::${TAGS}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.image_tags.outputs.tags }}
